# command : `$ docker-compose up -d`
version: '3.2'

services:
    db:
        image: postgres:9.6-alpine
        environment:
            - POSTGRES_DB=4AIW3-symfony
            - POSTGRES_USER=api-platform
            - POSTGRES_PASSWORD=lmdpe
        ports:
            - "5432:5432"

volumes:
    db-data: {}
